version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    reviewers:
      - "az-digital/developers"
      - "az-digital/maintainers"
    labels:
      - "dependences"
      - "github-actions"
      - "ci"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    reviewers:
      - "az-digital/developers"
      - "az-digital/maintainers"
    labels:
      - "dependences"
      - "github-actions"
      - "ci"
      - "2.x only"